### PR TITLE
Fix conan package url

### PR DESCRIPTION
**Pull request by mgk-github**

### CODE REVIEW

**Review by matthieu-deveau-pix4d — APPROVED** [review]

**Review by SyrianSpock — APPROVED** [review]

**Review by klaussnd — APPROVED** [review]

**Comment by mgk-github** [comment]
Hello,
What is the next step with this PR ? Merge it ?

**Review by aledegano — APPROVED** [review]
Thank you for this :)

**Comment by aledegano** [comment]
> Hello,
> What is the next step with this PR ? Merge it ?

Yes, you can merge it. The conan-builder will take care of building and uploading the new recipe.

**Comment by mgk-github** [comment]
Ok thanks

**Pull request merged**
